server.port=8083
spring.application.name=sanosysalvos-bff

spring.mvc.cors.allowed-origins=http://localhost:8080,http://localhost:3000
spring.mvc.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.mvc.cors.allowed-headers=*


microservicio.organizaciones.url=http://localhost:8081/api/organizaciones
microservicio.coincidencias.url=http://localhost:8084/api/coincidencias
microservicio.pet.url=http://localhost:8082/api/pet
microservicio.geolocalizacion.url=http://localhost:8085/api/geolocalizacion
microservicio.usuarios.url=http://localhost:8087/api/users
microservicio.login.url=http://localhost:8089/api/login
microservicio.notificaciones.url=http://localhost:8086/api/notifications
microservicio.auth.url=http://localhost:8088/api/auth